#!/usr/bin/env bash
# update-agent-context.sh — refresh the auto-generated "Active feature snapshot"
# block in CLAUDE.md from the current plan.md + feature.json.
#
# Only the content between the AGENT-CONTEXT markers is touched; hand-written
# standing rules elsewhere in CLAUDE.md are left intact. Idempotent. Never fails
# the caller (always exit 0). Run automatically by the after_plan hook.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT" || exit 0

CLAUDE="CLAUDE.md"
[ -f "$CLAUDE" ] || { echo "[agent-context] no CLAUDE.md; skipping"; exit 0; }

FEATURE_DIR=""
[ -f .specify/feature.json ] && FEATURE_DIR="$(sed -n 's/.*"feature_directory"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' .specify/feature.json | head -1)"
PLAN="$FEATURE_DIR/plan.md"
BRANCH="$(git branch --show-current 2>/dev/null || echo '')"

# Pull a "**Label**: value" field out of plan.md, collapsing a wrapped
# (multi-line, blank-line-terminated) value into a single line.
get_field() {
  [ -f "$PLAN" ] || return 0
  awk -v label="$1" '
    BEGIN { pat = "^\\*\\*" label "\\*\\*:[[:space:]]*" }
    $0 ~ pat { grab=1; sub(pat,""); buf=$0; next }
    grab && /^[[:space:]]*$/ { print buf; grab=0; exit }
    grab { sub(/^[[:space:]]+/,""); buf = buf " " $0 }
    END { if (grab) print buf }
  ' "$PLAN"
}
LANG="$(get_field 'Language/Version')"
DEPS="$(get_field 'Primary Dependencies')"
STORAGE="$(get_field 'Storage')"
PTYPE="$(get_field 'Project Type')"

START="<!-- AGENT-CONTEXT:START (auto-generated by update-agent-context.sh — do not edit by hand) -->"
END="<!-- AGENT-CONTEXT:END -->"

BLOCK="$START
## Active feature snapshot (auto-generated — see the spec/plan for authority)

- Feature: ${FEATURE_DIR:-(none)} on branch \`${BRANCH:-(unknown)}\`
- Language: ${LANG:-(see plan.md)}
- Primary deps: ${DEPS:-(see plan.md)}
- Storage: ${STORAGE:-(see plan.md)}
- Project type: ${PTYPE:-(see plan.md)}
$END"

# Strip any existing block (inclusive of markers), then append the fresh one.
tmp="$(mktemp)"
awk -v s="$START" -v e="$END" '
  index($0,s){skip=1}
  !skip{print}
  index($0,e){skip=0; next}
' "$CLAUDE" > "$tmp"

printf '%s\n\n%s\n' "$(cat "$tmp")" "$BLOCK" > "$CLAUDE"
rm -f "$tmp"
echo "[agent-context] refreshed snapshot in CLAUDE.md (feature: ${FEATURE_DIR:-none})"
exit 0
